<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kendaraan;
use App\Models\TarifParkir;
use App\Models\LogAktivitas;
use App\Services\SepedaCodeGenerator;
use Illuminate\Support\Facades\Auth;

class KendaraanController extends Controller
{
    protected SepedaCodeGenerator $sepedaCodeGenerator;

    public function __construct(SepedaCodeGenerator $sepedaCodeGenerator)
    {
        $this->sepedaCodeGenerator = $sepedaCodeGenerator;
    }

    public function index()
    {
        $kendaraans = Kendaraan::all();
        $tarifParkirs = TarifParkir::where('status', 'aktif')->get();
        return view('admin.data-kendaraan', compact('kendaraans', 'tarifParkirs'));
    }

    public function store(Request $request)
    {
        $jenisKendaraanValid = TarifParkir::where('status', 'aktif')->pluck('jenis_kendaraan')->toArray();
        
        $jenis = $request->input('jenis');
        $isSepeda = strtolower($jenis) === 'sepeda';

        // Build validation rules dynamically
        $validationRules = [
            'jenis' => ['required', 'in:' . implode(',', $jenisKendaraanValid)],
            'warna' => 'required|string',
            'nama_pemilik' => 'required|string',
            'gambar' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ];

        // Plat nomor validation: wajib jika bukan sepeda, opsional jika sepeda
        if ($isSepeda) {
            $validationRules['plat_nomor'] = 'nullable|string';
        } else {
            $validationRules['plat_nomor'] = 'required|string|unique:kendaraans';
        }

        $request->validate($validationRules);

        $data = $request->except('gambar');

        // Untuk sepeda, biarkan observer handle auto-generation
        // Untuk kendaraan lain, gunakan input dari user
        if ($isSepeda && empty($data['plat_nomor'])) {
            // Will be auto-generated by observer
            $data['plat_nomor'] = '';
        }

        if ($request->hasFile('gambar')) {
            $file = $request->file('gambar');
            $path = $file->store('kendaraan', 'public');
            $data['gambar'] = $path;
        }

        $kendaraan = Kendaraan::create($data);
        
        // Log activity
        $user = Auth::user();
        $logMessage = $isSepeda 
            ? "Tambah kendaraan Sepeda (Kode: {$kendaraan->plat_nomor})"
            : "Tambah kendaraan {$request->plat_nomor} ({$request->jenis})";
        
        LogAktivitas::create([
            'user_id' => $user->id,
            'aktivitas' => $logMessage,
            'lokasi' => $user->penempatan ?? '-',
        ]);

        return back()->with('success', 'Kendaraan berhasil ditambahkan.' . ($isSepeda ? " Kode: {$kendaraan->plat_nomor}" : ''));
    }

    public function update(Request $request, $id)
    {
        $kendaraan = Kendaraan::findOrFail($id);
        $jenisKendaraanValid = TarifParkir::where('status', 'aktif')->pluck('jenis_kendaraan')->toArray();

        $jenis = $request->input('jenis');
        $isSepeda = strtolower($jenis) === 'sepeda';

        // Build validation rules dynamically
        $validationRules = [
            'jenis' => ['required', 'in:' . implode(',', $jenisKendaraanValid)],
            'warna' => 'required|string',
            'nama_pemilik' => 'required|string',
            'gambar' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ];

        // Plat nomor validation
        if ($isSepeda) {
            // Untuk sepeda, plat_nomor read-only (tidak boleh diubah)
            // Skip validation
            $validationRules['plat_nomor'] = 'nullable|string';
        } else {
            // Untuk kendaraan lain, plat_nomor bisa diubah tapi harus unique
            $validationRules['plat_nomor'] = 'required|string|unique:kendaraans,plat_nomor,' . $id;
        }

        $request->validate($validationRules);

        $data = $request->except('gambar');

        // Jika awalnya bukan sepeda tapi sekarang menjadi sepeda, observer akan generate kode
        // Jika tidak, gunakan input dari user

        if ($request->hasFile('gambar')) {
            $file = $request->file('gambar');
            $path = $file->store('kendaraan', 'public');
            $data['gambar'] = $path;
        }

        $kendaraan->update($data);
        
        // Log activity
        $user = Auth::user();
        $isSepedaNow = $kendaraan->isSepeda();
        $logMessage = $isSepedaNow
            ? "Update kendaraan Sepeda (Kode: {$kendaraan->plat_nomor})"
            : "Update kendaraan {$kendaraan->plat_nomor} ({$kendaraan->jenis})";
        
        LogAktivitas::create([
            'user_id' => $user->id,
            'aktivitas' => $logMessage,
            'lokasi' => $user->penempatan ?? '-',
        ]);

        return back()->with('success', 'Kendaraan berhasil diupdate.');
    }

    public function destroy($id)
    {
        $kendaraan = Kendaraan::findOrFail($id);
        $platNomor = $kendaraan->plat_nomor;
        $jenis = $kendaraan->jenis;
        $kendaraan->delete();
        
        // Log activity
        $user = Auth::user();
        $logMessage = $jenis === 'Sepeda'
            ? "Hapus kendaraan Sepeda (Kode: {$platNomor})"
            : "Hapus kendaraan {$platNomor}";
        
        LogAktivitas::create([
            'user_id' => $user->id,
            'aktivitas' => $logMessage,
            'lokasi' => $user->penempatan ?? '-',
        ]);

        return back()->with('success', 'Kendaraan berhasil dihapus.');
    }
}
